version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    permissions:
      - object: /var/www/html/wp-content
        pattern: "**"
        owner: www-data
        group: www-data
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root
 

  
