version: 0.2

phases:
  install:
    commands:
       - echo "CODE BUILD PART"
  
  pre_build:
    commands:
       - echo " prebuild part "
         export Databasename=$(aws ssm get-parameter --name /DB/NAME --with-decryption --query "Parameter.Value" --output text)
         export User=$(aws ssm get-parameter --name /DB/USER --with-decryption --query "Parameter.Value" --output text)
         export Password=$(aws ssm get-parameter --name /DB/PASSWORD --with-decryption --query "Parameter.Value" --output text)
         export Host=$(aws ssm get-parameter --name /DB/HOST --with-decryption --query "Parameter.Value" --output text)
         
                
  build:
    commands:
       - echo "build part "
         chmod +x ./scripts/before_install.sh
         ./scripts/before_install.sh

  post_build:
    commands:
       - echo "post build "
         echo "post post build"
       
artifacts:
  files:
  - "**/*"
