version: 0.2

phases:
  install:
    commands:
       - echo "CODE BUILD PART"
  
  pre_build:
    commands:
       - echo " prebuild part "
         chmod +x ./build_scripts/configuration.sh
         sh ./build_scripts/configuration.sh
       
       
  build:
    commands:
       - echo "build part "
      
  post_build:
    commands:
       - echo "post build "
       
artifacts:
  files:
  - "**/*"
