version: 0.2
env:
  shell: bash
  secrets-manager:
    key: aws:secretsmanager:ap-south-1:Databasename:800462127340:AWSCURRENT:5b9d880a-8c5d-404f-a314-c2aa99963c78"

phases:
  install:
    commands:
       - echo "CODE BUILD PART"
  
  pre_build:
    commands:
       - echo " prebuild part "
        
  build:
    commands:
     - SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id "aws:secretsmanager:ap-south-1:Databasename:800462127340:AWSCURRENT:5b9d880a-8c5d-404f-a314-c2aa99963c78" --query 'SecretString' --output text)
       # export MY_SECRET=$SECRET_VALUE
     - echo $SECRET_VALUE

  post_build:
    commands:
       - echo "post build "
               
artifacts:
  files:
  - "**/*"
