version: 0.2
env:
  shell: bash
  secrets-manager:
    key: "arn:aws:secretsmanager:ap-south-1:800462127340:secret:mydatabase_secrets-k97AKz"

phases:
  install:
    commands:
       - echo "CODE BUILD PART"
  
  pre_build:
    commands:
       - echo " prebuild part "
        
  build:
    commands:
     - SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id "arn:aws:secretsmanager:ap-south-1:800462127340:secret:mydatabase_secrets-k97AKz" --query SecretString --output text)
       # export MY_SECRET=$SECRET_VALUE
     - echo $SECRET_VALUE

  post_build:
    commands:
       - echo "post build "
               
artifacts:
  files:
  - "**/*"
