version: 0.2
env:
  shell: bash

phases:
  pre_build:
    commands:
        - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:551608844195:secret:Database_credentials-QFzmga --query SecretString)
        - export USER=$(echo "$SECRET_JSON" | jq -r 'fromjson | .DB_USER')
        - export PASSWORD=$(echo "$SECRET_JSON" | jq -r 'fromjson | .DB_PASSWORD')
        - export NAME=$(echo "$SECRET_JSON" | jq -r 'fromjson | .DB_NAME')

  build:
    commands:
      - echo "Build stage"
      - chmod +x ./scripts/builld.sh
      - ./scripts/builld.sh
      
     
  post_build:
    commands:
      - echo "post build "

artifacts:
  files:
    - "**/*"
