version: 0.2
env:
  shell: bash

phases:
  pre_build:
    commands:
        - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:ap-south-1:800462127340:secret:mydatabase_secrets-k97AKz --query SecretString)
        - export HOST=$(echo "$SECRET_JSON" | jq -r 'fromjson | .DB_HOST')
        - export USER=$(echo "$SECRET_JSON" | jq -r 'fromjson | .DB_USER')
        - export PASSWORD=$(echo "$SECRET_JSON" | jq -r 'fromjson | .DB_PASSWORD')
        - export NAME=$(echo "$SECRET_JSON" | jq -r 'fromjson | .DB_NAME')

  build:
    commands:
      - echo "Build stage"
      - chmod +x ./scripts/builld.sh
      - ./scripts/builld.sh
      
     
  post_build:
    commands:
      - echo "post build"

artifacts:
  files:
    - "**/*"
