version: 0.2

phases:
  install:
    commands:
       - echo "CODE BUILD PART"
  
  pre_build:
    commands:
       - echo " prebuild part "
         export DB_NAME=$(aws ssm get-parameter --name /DB/NAME --with-decryption --query "Parameter.Value" --output text)
         export DB_USER=$(aws ssm get-parameter --name /DB/USER --with-decryption --query "Parameter.Value" --output text)
         export DB_PASSWORD=$(aws ssm get-parameter --name /DB/PASSWORD --with-decryption --query "Parameter.Value" --output text)
         export DB_HOST=$(aws ssm get-parameter --name /DB/HOST --with-decryption --query "Parameter.Value" --output text)

                 
  build:
    commands:
       - echo "build part "
         sed -e "s|__DB_NAME__|${DB_NAME}|g" -e "s|__DB_USER__|${DB_USER}|g" -e "s|__DB_PASSWORD__|${DB_PASSWORD}|g" -e "s|__DB_HOST__|${DB_HOST}|g" wp-config.php.template > wp-config.php
    
      
  post_build:
    commands:
       - echo "post build "
         echo "post post build"
       
artifacts:
  files:
  - "**/*"
